<?php require_once(dirname(__DIR__) . '/init.php'); ?>
<?php
require_once __DIR__.'/../config.php';
require_once __DIR__.'/../includes/functions.php';
require_once __DIR__.'/../lib/poultry_diagnostics.php';
require_once __DIR__.'/../lib/investigation_followup.php';
require_once __DIR__.'/../includes/audit_helpers.php';
requireLogin(); requireBusinessReportAccess(); $farmId=requireCurrentFarmId();
$type=($_GET['type']??'layer')==='broiler'?'broiler':'layer'; $issue=(string)($_GET['issue']??($type==='layer'?'laying_decline':'mortality')); $cycleId=(int)($_GET['cycle_id']??0); $asOf=(string)($_GET['as_of']??date('Y-m-d'));
$followupError=null;$followupNotice=null;
try{$d=poultry_diagnostic_investigate($pdo,$farmId,$cycleId,$type,$issue,$asOf);}catch(Throwable $e){$d=null;$error=$e->getMessage();}
$episodeKey=$d?investigation_followup_episode_key('poultry',$issue,(string)$d['from_date'],(string)$d['to_date']):'';
$episodeAsOf=$d?(string)$d['to_date']:$asOf;
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='save_followup' && $d){
    if (!verify_csrf_token($_POST['csrf_token'] ?? '')) { http_response_code(419); exit('Invalid request token.'); }
    ensureAllowed(($type==='broiler'?'broiler_daily':'layer_daily'));
    try{
        $resolve=($_POST['followup_mode']??'')==='resolve';
        $fid=investigation_followup_save($pdo,$farmId,'poultry',$cycleId,$issue,$episodeAsOf,$episodeKey,(string)($_POST['outcome']??''),(string)($_POST['finding_notes']??''),(string)($_POST['action_taken']??''),$resolve,(int)($_SESSION['user_id']??0));
        audit_log_event($resolve?'resolve':'update','management_investigation',$fid,['investigation_type'=>'poultry','subject_id'=>$cycleId,'issue_type'=>$issue,'as_of_date'=>$episodeAsOf,'episode_key'=>$episodeKey,'outcome'=>(string)($_POST['outcome']??'')]);
        $followupNotice=$resolve?'Investigation outcome resolved and audit logged.':'Management follow-up saved and audit logged.';
    }catch(Throwable $e){$followupError=$e->getMessage();}
}
$followup=$d?investigation_followup_get($pdo,$farmId,'poultry',$cycleId,$issue,$episodeKey):null;
$priorFollowup=$d?investigation_followup_latest_prior($pdo,$farmId,'poultry',$cycleId,$issue,$episodeAsOf,$episodeKey):null;
$priorHistory=$d?investigation_followup_prior_history($pdo,$farmId,'poultry',$cycleId,$issue,$episodeAsOf,$episodeKey):[];
function inv_href($p){return rtrim(BASE_URL,'/').'/'.ltrim($p,'/');}
?>
<!doctype html><html><head><?php include __DIR__.'/../navbar_head.php';?><title>Poultry Investigation - Renee Farms</title><style>
.inv-shell{max-width:1180px;margin:auto}.inv-hero{border-left:3px solid var(--bs-warning)}.inv-evidence{border:1px solid var(--bs-border-color);border-radius:.6rem}.inv-row{padding:.7rem .8rem;border-bottom:1px solid var(--bs-border-color)}.inv-row:last-child{border:0}.inv-dot{width:30px;height:30px;border-radius:8px;display:flex;align-items:center;justify-content:center;flex:0 0 30px}.inv-check{padding:.45rem .6rem;border:1px solid var(--bs-border-color);border-radius:.45rem;margin-bottom:.4rem}.inv-muted{line-height:1.35}.inv-timeline{position:relative;padding-left:1.1rem}.inv-timeline:before{content:"";position:absolute;left:.32rem;top:.35rem;bottom:.35rem;border-left:2px solid var(--bs-border-color)}.inv-time-row{position:relative;padding:0 0 .8rem 1rem}.inv-time-row:last-child{padding-bottom:0}.inv-time-dot{position:absolute;left:-.98rem;top:.3rem;width:.55rem;height:.55rem;border-radius:50%;background:var(--bs-secondary);box-shadow:0 0 0 3px var(--bs-body-bg)}.inv-time-date{font-size:.75rem;color:var(--bs-secondary-color);font-weight:600}.inv-time-detail{font-size:.82rem;color:var(--bs-secondary-color);line-height:1.3}
</style></head><body><?php include __DIR__.'/../navbar.php';?><div class="container-fluid py-3"><div class="inv-shell">
<div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3 app-responsive-toolbar"><div><h3 class="mb-0"><i class="bi bi-search-heart"></i> Poultry Investigation</h3><div class="small text-muted">Evidence-led review of recorded farm data. Findings indicate patterns to check; they are not a veterinary diagnosis.</div></div><a class="btn btn-sm btn-outline-secondary" href="<?=inv_href('management/intelligence.php')?>"><i class="bi bi-arrow-left"></i> Farm Intelligence</a></div>
<?php if(isset($error)):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php elseif($d):?>
<div class="card inv-hero mb-3"><div class="card-body py-3"><div class="row g-2 align-items-center"><div class="col-lg-7"><div class="small text-uppercase text-muted fw-semibold"><?=htmlspecialchars($d['cycle']['cycle_code'])?> · <?=htmlspecialchars(ucfirst($d['production_type']))?></div><h4 class="mb-1"><?=htmlspecialchars($d['headline'])?></h4><strong><?=htmlspecialchars($d['measure'])?></strong></div><div class="col-lg-5 text-lg-end"><span class="badge bg-<?=$d['evidence_strength']==='Strong'?'success':($d['evidence_strength']==='Moderate'?'warning text-dark':'secondary')?>">Evidence strength: <?=htmlspecialchars($d['evidence_strength'])?></span><div class="small text-muted mt-1">Based on <?=$d['records_count']?> available daily record(s) through <?=htmlspecialchars(date('M j, Y',strtotime($d['as_of'])))?></div></div></div></div></div>
<div class="row g-3"><div class="col-lg-7"><div class="inv-evidence"><div class="px-3 py-2 bg-body-tertiary border-bottom"><strong>What the records show</strong></div><?php foreach($d['evidence'] as $e): $cls=$e['type']==='possible'?'warning':($e['type']==='observed'?'primary':'secondary');?><div class="inv-row d-flex gap-2"><span class="inv-dot bg-<?=$cls?>-subtle text-<?=$cls?>"><i class="bi <?=$e['type']==='possible'?'bi-exclamation-triangle':'bi-journal-check'?>"></i></span><div><div class="fw-semibold"><?=htmlspecialchars($e['title'])?></div><div class="small text-muted inv-muted"><?=htmlspecialchars($e['detail'])?></div></div></div><?php endforeach;?><?php if(!$d['evidence']):?><div class="p-3 text-muted">Not enough recorded evidence is available yet.</div><?php endif;?></div></div>
<div class="card mt-3"><div class="card-header py-2 fw-semibold">Evidence timeline <span class="fw-normal small text-muted">· recorded sequence, not causation</span></div><div class="card-body py-3"><div class="inv-timeline"><?php foreach(($d['timeline']??[]) as $t):?><div class="inv-time-row"><span class="inv-time-dot"></span><div class="inv-time-date"><?=htmlspecialchars(date('M j, Y',strtotime($t['date'])))?></div><div class="fw-semibold small"><?=htmlspecialchars($t['title'])?></div><div class="inv-time-detail"><?=htmlspecialchars($t['detail'])?></div></div><?php endforeach;?><?php if(empty($d['timeline'])):?><div class="small text-muted">No dated evidence is available for the current investigation window.</div><?php endif;?></div></div></div></div>
<div class="col-lg-5"><div class="card mb-3"><div class="card-header py-2 fw-semibold">Suggested management checks</div><div class="card-body py-2"><?php foreach($d['checks'] as $c):?><div class="inv-check"><i class="bi bi-square me-2"></i><?=htmlspecialchars($c)?></div><?php endforeach;?><div class="small text-muted mt-2">These are review steps, not medication or disease prescriptions.</div></div></div>
<?php if($d['missing']):?><div class="card mb-3"><div class="card-header py-2 fw-semibold">Evidence gaps</div><div class="card-body py-2"><ul class="small mb-0"><?php foreach($d['missing'] as $m):?><li class="mb-1"><?=htmlspecialchars($m)?></li><?php endforeach;?></ul></div></div><?php endif;?>
<?php if(!empty($priorHistory)):?><div class="card mb-3 border-secondary"><div class="card-header py-2 fw-semibold d-flex justify-content-between align-items-center"><span>Investigation history <span class="small text-muted fw-normal">· Previous investigations</span></span><span class="badge bg-secondary"><?=count($priorHistory)?> previous</span></div><div class="card-body py-2 small"><div class="text-muted mb-2">Historical management reviews are retained permanently. They do not resolve or alter the current evidence window.</div><?php foreach($priorHistory as $hist):?><div class="border rounded p-2 mb-2"><div class="d-flex justify-content-between gap-2 flex-wrap"><strong><?=htmlspecialchars(date('M j, Y',strtotime($hist['as_of_date'])))?> investigation</strong><span class="badge bg-<?=($hist['status']??'open')==='resolved'?'secondary':'warning text-dark'?>"><?=htmlspecialchars(ucfirst($hist['status']??'open'))?></span></div><div class="mt-1"><strong>Outcome:</strong> <?=htmlspecialchars(investigation_followup_outcomes()[$hist['outcome']??'']??ucwords(str_replace('_',' ',(string)($hist['outcome']??''))))?></div><?php if(!empty($hist['finding_notes'])):?><div class="mt-1"><strong>Finding:</strong> <?=htmlspecialchars($hist['finding_notes'])?></div><?php endif;?><?php if(!empty($hist['action_taken'])):?><div><strong>Action:</strong> <?=htmlspecialchars($hist['action_taken'])?></div><?php endif;?><div class="text-muted mt-1">Recorded by <?=htmlspecialchars($hist['recorded_by_name']??'user')?><?php if(!empty($hist['resolved_at'])):?> · resolved <?=htmlspecialchars(date('M j, Y g:i a',strtotime($hist['resolved_at'])))?><?php endif;?></div></div><?php endforeach;?></div></div><?php endif;?>
<div class="card mb-3"><div class="card-header py-2 fw-semibold d-flex justify-content-between align-items-center"><span>Management follow-through<?php if(!$followup):?> <span class="small text-muted fw-normal">· New investigation episode</span><?php endif;?></span><?php if($followup):?><span class="badge bg-<?=($followup['status']??'open')==='resolved'?'success':'warning text-dark'?>"><?=htmlspecialchars(ucfirst($followup['status']))?></span><?php endif;?></div><div class="card-body py-2">
<?php if($followupNotice):?><div class="alert alert-success py-2 small"><?=htmlspecialchars($followupNotice)?></div><?php endif;?><?php if($followupError):?><div class="alert alert-danger py-2 small"><?=htmlspecialchars($followupError)?></div><?php endif;?>
<p class="small text-muted">Record what management checked and found. This follow-through does not edit Daily Records, weights, health events, inventory, sales or other source history.</p>
<form method="post" class="app-responsive-form">
<input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrf_token(),ENT_QUOTES)?>"><input type="hidden" name="action" value="save_followup">
<div class="mb-2"><label class="form-label small fw-semibold">Outcome</label><select class="form-select form-select-sm" name="outcome" required><option value="">Select outcome</option><?php foreach(investigation_followup_outcomes() as $k=>$v):?><option value="<?=htmlspecialchars($k)?>" <?=($followup['outcome']??'')===$k?'selected':''?>><?=htmlspecialchars($v)?></option><?php endforeach;?></select></div>
<div class="mb-2"><label class="form-label small fw-semibold">What management found</label><textarea class="form-control form-control-sm" name="finding_notes" rows="3" required><?=htmlspecialchars($followup['finding_notes']??'')?></textarea></div>
<div class="mb-2"><label class="form-label small fw-semibold">Action taken / next step</label><textarea class="form-control form-control-sm" name="action_taken" rows="2"><?=htmlspecialchars($followup['action_taken']??'')?></textarea></div>
<div class="d-flex gap-2 flex-wrap"><button class="btn btn-sm btn-outline-primary" name="followup_mode" value="save" onclick="this.form.removeAttribute('data-confirm')">Save follow-up</button><button class="btn btn-sm btn-success" name="followup_mode" value="resolve" onclick="this.form.setAttribute('data-confirm','Resolve this investigation with the recorded management finding? Source records will not be changed.');this.form.setAttribute('data-confirm-title','Resolve investigation?');this.form.setAttribute('data-confirm-button','Resolve Investigation');this.form.setAttribute('data-confirm-tone','primary')">Resolve investigation</button></div>
<?php if($followup):?><div class="small text-muted mt-2">Last recorded by <?=htmlspecialchars($followup['recorded_by_name']??'user')?><?=!empty($followup['updated_at'])?' · '.htmlspecialchars(date('M j, Y g:i a',strtotime($followup['updated_at']))):''?><?php if(($followup['status']??'')==='resolved'&&!empty($followup['resolved_at'])):?> · resolved <?=htmlspecialchars(date('M j, Y g:i a',strtotime($followup['resolved_at'])) )?><?php endif;?></div><?php endif;?>
</form></div></div>
<div class="d-grid gap-2"><a class="btn btn-outline-primary btn-sm" href="<?=inv_href($d['daily_url'])?>">Review Daily Records</a><a class="btn btn-outline-primary btn-sm" href="<?=inv_href('poultry/health.php?production_type='.urlencode($d['production_type']).'&cycle_id='.(int)$d['cycle']['id'])?>">Review Health & Treatment</a><a class="btn btn-outline-primary btn-sm" href="<?=inv_href('inventory.php')?>">Review Inventory</a></div></div></div>
<?php endif;?></div></div></body></html>
