-- V2.2.50 Batch 3B — versioned Production-Entry Economic Basis
-- Approved rows are append-only application records. Revisions create a new version.
CREATE TABLE IF NOT EXISTS poultry_production_entry_snapshots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    farm_id INT NOT NULL,
    cycle_id INT NOT NULL,
    version_no INT NOT NULL,
    snapshot_status ENUM('original','revised') NOT NULL,
    entry_model ENUM('farm_reared','purchased_point_of_lay') NOT NULL,
    production_entry_date DATE NOT NULL,
    rearing_start_date DATE NULL,
    rearing_end_date DATE NULL,
    acquisition_basis DECIMAL(16,2) NOT NULL DEFAULT 0,
    feed_consumed_cost DECIMAL(16,2) NOT NULL DEFAULT 0,
    operating_inventory_cost DECIMAL(16,2) NOT NULL DEFAULT 0,
    direct_expenses DECIMAL(16,2) NOT NULL DEFAULT 0,
    explicit_shared_allocations DECIMAL(16,2) NOT NULL DEFAULT 0,
    attributed_investment DECIMAL(16,2) NOT NULL,
    production_entry_headcount INT NOT NULL,
    investment_per_entry_bird DECIMAL(16,2) NOT NULL,
    unallocated_shared_cost_pool DECIMAL(16,2) NOT NULL DEFAULT 0,
    source_fingerprint CHAR(64) NOT NULL,
    revision_category ENUM('production_entry_confirmation','source_transaction_correction','missing_historical_transaction','allocation_correction','production_entry_headcount_correction','administrative_correction') NOT NULL,
    revision_reason VARCHAR(500) NULL,
    previous_snapshot_id BIGINT UNSIGNED NULL,
    approved_by INT NULL,
    approved_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_poultry_entry_snapshot_version (farm_id,cycle_id,version_no),
    KEY idx_poultry_entry_snapshot_current (farm_id,cycle_id,approved_at),
    KEY idx_poultry_entry_snapshot_previous (previous_snapshot_id),
    CONSTRAINT fk_poultry_entry_snapshot_cycle FOREIGN KEY (cycle_id) REFERENCES production_cycles(id) ON DELETE CASCADE,
    CONSTRAINT fk_poultry_entry_snapshot_previous FOREIGN KEY (previous_snapshot_id) REFERENCES poultry_production_entry_snapshots(id) ON DELETE SET NULL,
    CONSTRAINT fk_poultry_entry_snapshot_user FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
