CREATE TABLE IF NOT EXISTS poultry_health_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    farm_id INT NOT NULL,
    cycle_id INT NULL,
    production_type ENUM('layer','broiler') NOT NULL,
    event_date DATE NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    product_name VARCHAR(150) NULL,
    dosage VARCHAR(120) NULL,
    reason_symptoms TEXT NULL,
    notes TEXT NULL,
    stock_item_id INT NULL,
    recorded_by INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_phe_farm_date (farm_id, event_date),
    INDEX idx_phe_cycle_date (cycle_id, event_date),
    INDEX idx_phe_type_date (farm_id, production_type, event_date),
    INDEX idx_phe_stock_item (stock_item_id),
    CONSTRAINT fk_phe_farm FOREIGN KEY (farm_id) REFERENCES farms(id) ON DELETE RESTRICT,
    CONSTRAINT fk_phe_cycle FOREIGN KEY (cycle_id) REFERENCES production_cycles(id) ON DELETE SET NULL,
    CONSTRAINT fk_phe_stock_item FOREIGN KEY (stock_item_id) REFERENCES stock_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_phe_user FOREIGN KEY (recorded_by) REFERENCES users(id) ON DELETE SET NULL
);
